# Q1

In [ ]:
a = ["sam","45",888,5.4]
print(type(a))
a = tuple(a)
print(a)
print(type(a))

<class 'list'>
('sam', '45', 888, 5.4)
<class 'tuple'>


# Q2

In [ ]:
a = {"Roll_No":"CB.EN.U4CSE20254","Last_Name":"Adithya","First_Name":"Sanjay","DOB":"05/03/2003"}
print(a)
print(type(a))
print(a.keys())
print(a.values())

{'Roll_No': 'CB.EN.U4CSE20254', 'Last_Name': 'Adithya', 'First_Name': 'Sanjay', 'DOB': '05/03/2003'}
<class 'dict'>
dict_keys(['Roll_No', 'Last_Name', 'First_Name', 'DOB'])
dict_values(['CB.EN.U4CSE20254', 'Adithya', 'Sanjay', '05/03/2003'])


# Q3

In [ ]:
import numpy as np

np.random.seed()
print(np.random.rand(4,3))

[[0.53684034 0.94824821 0.67972089]
 [0.64484132 0.2928819  0.76143065]
 [0.76343158 0.08080466 0.42783726]
 [0.62244634 0.75271652 0.63815186]]


# Q4

In [ ]:
import numpy as np

print(np.random.uniform(1,2))
print(abs(-1234))

1.5831454270569365
1234


# Q5

In [ ]:
import numpy as np
def return_rand():
  return np.random.randint(10,90)

return_rand()


19

# Q6

In [ ]:
import numpy as np

a = [1,2,3,4,5]

print(a)
np.random.shuffle(a)
print("After Shuffling: ",a)


print(a[:3])

print(a[3])


[1, 2, 3, 4, 5]
After Shuffling:  [1, 5, 3, 2, 4]
[1, 5, 3]
2


# Q7

In [ ]:
f = open("marvel.txt","r+")
f.write("Wakanda Forever!!!!!!!! SIUUUUUUUUUUUUUUUUUUUUUUUUUUU!!!!")
f.close()

f = open("marvel.txt","r")
print(f.read())
f.close()

FileNotFoundError: ignored

# Q8

In [ ]:
def if_elif_else(n):
  if(n<0):
    print("Negative number!!")
  elif(n>0):
    print("Positive number!!")
  else:
    print("Zero!!")

if_elif_else(10)
if_elif_else(-40)
if_elif_else(0)

Positive number!!
Negative number!!
Zero!!


In [ ]:
def for_while(n):
  for i in range(n):
    print(n-i,end=" ")

  print()

  while(n>0):
    n-=1
    if(n==5):
      continue
    elif(n==2):
      break
    print(n,end=" ")
  
for_while(10)

10 9 8 7 6 5 4 3 2 1 
9 8 7 6 4 3 

# Q9

In [ ]:
a = "The King is dead, Long Live the King"

print(a)
print(a[0])
print(a[2:5])
print(a[2:])

print(a.split())
print(a.split("i"))

The King is dead, Long Live the King
T
e K
e King is dead, Long Live the King
['The', 'King', 'is', 'dead,', 'Long', 'Live', 'the', 'King']
['The K', 'ng ', 's dead, Long L', 've the K', 'ng']


# Q10

In [ ]:
import numpy as np

a = [1.0,4.0,5.0,8.0]
print(type(a))

a = np.array(list(map(int,a)))
print(type(a))

print(a[:2])

<class 'list'>
<class 'numpy.ndarray'>
[1 4]


# Q11

In [ ]:
import numpy as np

a = [1,2,3,4,5,6]

a = np.array(a)
a = a.reshape(2,3)
print(a)


[[1 2 3]
 [4 5 6]]


# Q12

In [ ]:
import numpy as np

a = [1,2,3,4,5,6]

a = np.array(a)
a = a.reshape(2,3)

print(a[1])

print("[",end="")
for i in a:
  for j in i:
    print(j,end="., ")
print("]")

print(a.shape)
print(len(a))

[4 5 6]
[1., 2., 3., 4., 5., 6., ]
(2, 3)
2


# Q13

In [ ]:
import numpy as np

n = 10
a = np.array(np.arange(1,n+1))
print(a)

a = a.reshape(2,5)
print(a)

a = a.transpose()
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


# Q14

In [ ]:
import numpy as np

a = [1,2,3]
a = np.array(a)

print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


# Q15

In [ ]:
import numpy as np

a = [1,2,3]
a.append([9,9,9])
print(a)

[1, 2, 3, [9, 9, 9]]


# Q16

In [ ]:
a = [2,4,5]

sum = 0

for i in a:
  sum+=i

print(sum)

11


# Q17

In [ ]:
a = [77,74,75]

prod = 1

for i in a:
  prod*=i

print(prod)

427350


# Q18

In [ ]:
import numpy as np

a = [2,1,9,1,2,22,1,1,4,55,6,2,56]

print(np.mean(a))
print(np.var(a))
print(max(a))
print(min(a))
print(np.argmin(a))
#print(np.median(a))
print(a[(len(a)+1)//2])
print(np.argmax(a))
print(np.std(a))

12.461538461538462
367.32544378698225
56
1
1
1
12
19.165736192147232


# Q19

In [ ]:
import numpy as np

a = [1, 1, 4, 5, 5, 5, 7]

a = np.array(a)

b = np.unique(a)
print(a)
print(b)

np.sort(b)
print(b)

[1 1 4 5 5 5 7]
[1 4 5 7]
[1 4 5 7]


# Q20

In [ ]:
import numpy as np

a = [1,2,3]
b = [0,1,1]

print(np.dot(a,b))

5


# Q21

In [ ]:
import numpy as np

a = np.array([[2,-12],[1,-5]])
w,v = np.linalg.eig(a)
print(w)
print(v)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


# Q22

In [ ]:
import numpy as np

a = [11, 22, 11, 31]
b = [25, 33, 31, 28]

print(np.corrcoef(a,b))

[[1.         0.15997968]
 [0.15997968 1.        ]]
